In [ ]:
#Q1. Write a python function that takes two matrices (A, B) of size n×n as an input and returns
#an output matrix C, where C = A × B. Test your function by taking two simple 3 × 3 matrices
#and compare your result with Numpy’s inbuilt function ”np.matmul(A,B)”.

import numpy as np
import sys

def mul(r1,c1,r2,c2,a,b):

  c = np.zeros((r1,c2))

  if(c1!=r2):
    sys.exit("c1 and r2 must be equal for matrix multiplication")

  for i in range(r1):
    for j in range(c1):
      a[i, j] = np.random.randint(1,10)

  for i in range(r2):
    for j in range(c2):
      b[i, j] = np.random.randint(1,10)

  for i in range(r1):
    for j in range(c2):
      for k in range(c1):
        c[i, j] += a[i, k]*b[k, j]

  return c

r1 = 6
c1 = 7
r2 = 7
c2 = 6

a = np.zeros((r1,c1))
b = np.zeros((r2,c2))

for i in range(r1):
  for j in range(c1):
    a[i, j] = np.random.randint(1,10)

for i in range(r2):
  for j in range(c2):
    b[i, j] = np.random.randint(1,10)

print('A is:\n', a,'\nB is:\n',b,'\n')
print('A*B is:\n', mul(r1,c1,r2,c2,a,b))

print('\nUsing matmul:\n', np.matmul(a,b),'\n\n')



A is:
 [[2. 3. 5. 7. 9. 6. 8.]
 [7. 1. 9. 2. 5. 9. 9.]
 [7. 7. 1. 6. 4. 4. 5.]
 [8. 5. 6. 7. 3. 9. 7.]
 [8. 5. 2. 7. 7. 5. 4.]
 [6. 2. 1. 2. 1. 4. 5.]] 
B is:
 [[2. 9. 1. 6. 7. 5.]
 [5. 1. 9. 9. 5. 4.]
 [2. 3. 9. 1. 7. 8.]
 [7. 3. 1. 3. 4. 9.]
 [1. 8. 7. 9. 2. 5.]
 [3. 2. 1. 7. 5. 9.]
 [5. 2. 3. 2. 3. 2.]] 

A*B is:
 [[168. 207. 239. 238. 230. 255.]
 [130. 171. 217. 245. 301. 252.]
 [157. 187. 217. 220. 170. 227.]
 [160. 211. 187. 245. 220. 236.]
 [ 66.  90. 124. 124. 139. 126.]
 [107. 142. 190. 175. 231. 173.]]

Using matmul:
 [[168. 207. 239. 238. 230. 255.]
 [130. 171. 217. 245. 301. 252.]
 [157. 187. 217. 220. 170. 227.]
 [160. 211. 187. 245. 220. 236.]
 [ 66.  90. 124. 124. 139. 126.]
 [107. 142. 190. 175. 231. 173.]] 




In [1]:
#Q2. LU Decomposition

import numpy as np

def lu_decom(n,m):

  l = np.zeros((n, n))
  u = np.zeros((n ,n))

  #s1 = 0
  #s2 = 0
  #for i in range(r):
   # for j in range(c):
    #  u[i, i] = 1
     # if(i < j):
      #  for k in range((i-1)):
       #   s1 += l[i, k] * u[k, j]
        #u[i, j] = (m[i, j] - s1)/l[i, i]
       #
      #elif(i>=j):
       # for k in range((j-1)):
        #  s2 += l[i, k] * u[k, j]
        #l[i, j] = m[i, j] - s2

  for i in range(n):

    for j in range(n):
      #s = 0
      if(j < i):
        l[j, i] = 0
      else:
        l[j, i] = m[j, i]
        for k in range(i):
          #s += l[i, k] * u[k, j]
          l[j, i] = l[j, i] - l[j, k] * u[k, i]

    for j in range(n):
      #s = 0
      if(j < i):
        u[i, j] = 0
      elif(j == i):
        u[i, j] = 1
      else:
        u[i, j] = m[i, j] * (1/l[i, i])
        for k in range(i):
          #s += l[i, k] * u[k, j]
          u[i, j] = u[i, j] - ((l[i, k] * u[k, j]) * (1/l[i, i]))
     # u[i, i] = 1



  return l, u


n = 4

m = np.zeros((n, n))
l = np.zeros((n ,n))
u = np.zeros((n, n))

for i in range(n):
  for j in range(n):
    m[i, j] = np.random.randint(1,10)

l, u = lu_decom(n ,m)

print('The matrix to work with is:\n', m, '\n\n','The L matrix is:\n', l,'\n\nThe U matrix is:\n', u, '\n\n')

#Multiplying L and U

m2 = np.zeros((n, n))

m2 = np.matmul(l,u)

print('L*U gives:\n\n', m2)




The matrix to work with is:
 [[2. 5. 6. 3.]
 [8. 6. 7. 1.]
 [4. 2. 6. 6.]
 [1. 9. 3. 8.]] 

 The L matrix is:
 [[  2.           0.           0.           0.        ]
 [  8.         -14.           0.           0.        ]
 [  4.          -8.           3.71428571   0.        ]
 [  1.           6.5         -7.89285714  14.75      ]] 

The U matrix is:
 [[1.         2.5        3.         1.5       ]
 [0.         1.         1.21428571 0.78571429]
 [0.         0.         1.         1.69230769]
 [0.         0.         0.         1.        ]] 


L*U gives:

 [[2. 5. 6. 3.]
 [8. 6. 7. 1.]
 [4. 2. 6. 6.]
 [1. 9. 3. 8.]]
